### ISSUE TITLE
报错 Error: the object capabilities  

### ISSUE THREAD

**Issue by Arvingrep** [yaniswang/jWebDriver#34]
系统环境： 
 docker version
``` 
Client: Docker Engine - Community
 Version:           20.10.1

docker-compose.yml 内容：
``` 

```
# To start Docker in Swarm mode, you need to run `docker swarm init`
# To deploy the Grid, `docker stack deploy -c docker-compose.yml grid`
# Stop with `docker stack rm grid`


version: '3.7'

services:
  hub:
   image: selenium/hub:3.141.59
   environment:
    TZ: Asia/Shanghai
    JAVA_OPTS: -Xmx8192m
    POOL_MAX: 30000
    GRID_NEW_SESSION_WAIT_TIMEOUT: -1
    GRID_JETTY_MAX_THREADS: -1
    GRID_NODE_POLLING: 5000
    GRID_CLEAN_UP_CYCLE: 5000
    GRID_TIMEOUT: 120
    GRID_BROWSER_TIMEOUT: 120
    GRID_MAX_SESSION: 18000
    GRID_UNREGISTER_IF_STILL_DOWN_AFTER: 120
    GRID_DEBUG: "true"
   ports:
     - "4444:4444"

  chrome:
    image:  selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
        replicas: 10
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
```
报错：

```
commons/start_mode/start_mode_Inte : chrome
    1) "before all" hook
    2) "after all" hook


  0 passing (724ms)
  2 failing

  1) commons/start_mode/start_mode_Inte : chrome
       "before all" hook:
     Error: the object {
  "capabilities": {
    "acceptInsecureCerts": false
    "browserName": "chrome"
    "browserVersion": "88.0.4324.96"
    "chrome": {
      "chromedriverVersion": "88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/b
      "userDataDir": "/tmp/.com.google.Chrome.baFK1C"
    }
    "goog:chromeOptions": {
      "debuggerAddress": "localhost:41536"
    }
    "networkConnectionEnabled": false
    "pageLoadStrategy": "normal"
    "platformName": "linux"
    "proxy": {}
    "setWindowRect": true
    "strictFileInteractability": false
    "timeouts": {
      "implicit": 0
      "pageLoad": 300000
      "script": 30000
    }
    "unhandledPromptBehavior": "dismiss and notify"
    "webauthn:extension:largeBlob": true
    "webauthn:virtualAuthenticators": true
    "webdriver.remote.sessionid": "490f0dca7efedf7a4e8d7f537d5980b1"
  }
  "sessionId": "490f0dca7efedf7a4e8d7f537d5980b1"
} was thrown, throw an Error :)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

```
